require("lazy").setup({
	"tpope/vim-surround",
	require("plugins.catppuccin"),
	require("plugins.lualine"),
	require("plugins.treesitter"),
	require("plugins.telescope"),
	require("plugins.lspconfig"),
	require("plugins.cmp"),
	require("plugins.fugitive"),
	require("plugins.gitsigns"),
	require("plugins.colorizer"),
	require("plugins.indent-lines"),
	require("plugins.autopairs"),
	require("plugins.oil"),
	require("plugins.undotree"),
	require("plugins.conform"),
	require("plugins.saga"),
	require("plugins.trouble"),
	require("plugins.tsc"),
	require("plugins.mini-ai"),
}, {
	ui = {
		icons = vim.g.have_nerd_font and {} or {
			cmd = "⌘",
			config = "🛠",
			event = "📅",
			ft = "📂",
			init = "⚙",
			keys = "🗝",
			plugin = "🔌",
			runtime = "💻",
			require = "🌙",
			source = "📄",
			start = "🚀",
			task = "📌",
			lazy = "💤 ",
		},
	},
})
